dag_ids:
  one_hour: 
    dag_id: 'one_hour'
    tf_id: 'now 1-H'
    schedule: '*/10 * * * *'
    catchup: False
  four_hour:
    dag_id: 'four_hour'
    tf_id: 'now 4-H'
    schedule: '*/10 * * * *'
    catchup: False
  one_day:
    dag_id: 'one_day'
    tf_id: 'now 1-d'
    schedule:  '0 * * * *'
    catchup: False
  one_week:
    dag_id: 'one_week'
    tf_id: 'now 7-d'
    schedule:  '0 * * * *'
    catchup: False
  one_month: 
    dag_id: 'one_month'
    tf_id: 'today 1-m'
    schedule:  '0 0 * * *'
    catchup: False
  three_month:
    dag_id: 'three_month'
    tf_id: 'today 3-m'
    schedule:  '0 0 * * *'
    catchup: False
  one_year:
    dag_id: 'one_year'
    tf_id: 'today 12-m'
    schedule:  '0 0 * * *'
    catchup: False